name: CI Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker Compose
    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d --build

    # 3. Esperar a que los servicios estén disponibles
    - name: Wait for services to be ready
      run: |
        echo "Esperando a que los servicios estén disponibles..."
        for i in {1..20}; do
          if curl -s http://localhost:5000 && curl -s http://localhost:5003/health; then
            echo "Servicios disponibles."
            exit 0
          fi
          echo "Esperando 5 segundos..."
          sleep 5
        done
        echo "Los servicios no se iniciaron correctamente."
        exit 1

    # 4. Ejecutar los tests
    - name: Run tests
      run: |
        pip install pytest pytest-html
        pytest --maxfail=5 --disable-warnings -v tests/ --html=report.html

    # 5. Guardar reportes de test
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html

    # 6. Apagar los servicios después de los tests
    - name: Shut down Docker Compose
      if: always()
      run: docker-compose -f docker-compose.yml down
