name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Build y push db_service
      - name: Build and push db_service image
        run: |
          REPO_NAME=${{ github.repository }}
          docker build -t ghcr.io/${REPO_NAME}/db_service:latest -f ./app/container_h4_Simple/db_container/Dockerfile ./app/container_h4_Simple/db_container
          docker push ghcr.io/${REPO_NAME}/db_service:latest

      # 4. Build y push app_service
      - name: Build and push app_service image
        run: |
          REPO_NAME=${{ github.repository }}
          docker build -t ghcr.io/${REPO_NAME}/app_service:latest -f ./app/container_h4_Simple/app_container/Dockerfile ./app/container_h4_Simple/app_container
          docker push ghcr.io/${REPO_NAME}/app_service:latest

      # 5. Build y push logs_service
      - name: Build and push logs_service image
        run: |
          REPO_NAME=${{ github.repository }}
          docker build -t ghcr.io/${REPO_NAME}/logs_service:latest -f ./app/container_h4_Simple/logs_container/Dockerfile ./app/container_h4_Simple/logs_container
          docker push ghcr.io/${REPO_NAME}/logs_service:latest
