name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Build y push db_service
      - name: Build and push db_service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/db_service:latest -f ./container-h4-Simple/db_service/Dockerfile ./container-h4-Simple/db_service
          docker push ghcr.io/${{ github.repository }}/db_service:latest

      # 4. Build y push app_service
      - name: Build and push app_service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/app_service:latest -f ./container-h4-Simple/app_container/Dockerfile ./container-h4-Simple/app_container
          docker push ghcr.io/${{ github.repository }}/app_service:latest

      # 5. Build y push logs_service
      - name: Build and push logs_service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/logs_service:latest -f ./container-h4-Simple/logs_container/Dockerfile ./container-h4-Simple/logs_container
          docker push ghcr.io/${{ github.repository }}/logs_service:latest
