name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 4. Instalar pipenv
      - name: Install pipenv
        run: pip install pipenv

      # 5. Instalar dependencias
      - name: Install dependencies
        run: pipenv install --dev

      # 6. Ejecutar pruebas
      - name: Run tests
        run: pipenv run pytest --junitxml=report.xml

      # 7. Subir informe de pruebas
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.xml
