name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3  # Verifica si hay v4 o versión más nueva disponible

      # 2. Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4  # Verifica si hay v5 o versión más nueva disponible
        with:
          python-version: '3.12'

      # 5. Instalar pipenv
      - name: Install pipenv
        run: pip install pipenv

      # 6. Instalar dependencias
      - name: Install dependencies
        run: pipenv install --dev

      # 7. Ejecutar pruebas
      - name: Run tests
        run: pipenv run pytest --junitxml=report.xml

      # 8. Subir informe de pruebas
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3  # Verifica si hay v4 o versión más nueva disponible
        with:
          name: test-report
          path: report.xml
